### ISSUE TITLE
Glue quit unexpectedly of typing 'tags' on the save image dialog

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1412] opened 2017-10-02 16:58 UTC
This issue happened for both 2D and 3D viewers, I think it's qtpy issue but couldn't found any related reports online. @astrofrog Any ideas about this? Thanks! Below is my version information:

Glue: 0.12.0.dev03935
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.3.1
setuptools: 36.5.0.post20170921
numpy: 1.13.1
matplotlib: 2.0.2
pandas: 0.20.3
astropy: 2.0.2
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.1.0
glue_vispy_viewers: 0.9.dev0
IPython: 5.4.1
qtconsole: 4.3.1
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.19.1
skimage: 0.13.0
pyavm: Not installed
spectral_cube: Not installed
astrodendro: Not installed
mock: 2.0.0
pytest: 3.2.1
plotly: 2.0.15

**Comment by astrofrog** [comment] 2017-10-14 08:52
@PennyQ - could you clarify this issue - what do you mean by typing 'tags'?

**Comment by PennyQ** [comment] 2017-10-18 15:44
@astrofrog I mean 'Tags' on the following save image dialog. Try type anything in the Tags textbox and Glue will quit immediately.

<img width="810" alt="screenshot 2017-10-18 11 42 37" src="https://user-images.githubusercontent.com/13411839/31728137-84316396-b3f9-11e7-889f-3d6913472c8b.png">

**Comment by astrofrog** [comment] 2018-03-21 10:14
I can't reproduce this, can you check if you still get this with the latest developer version?

**Comment by astrofrog** [comment] 2018-07-03 14:12
I've not been able to reproduce this, so I'll go ahead and close it.

**Closed by astrofrog** 2018-07-03 14:12 UTC
Labels: bug
