### ISSUE TITLE
Failure loading FITS file

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#792] opened 2015-11-18 16:19 UTC
I've been persistently getting the following error that I don't understand:
```
Traceback (most recent call last):
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/main.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/main.py", line 132, in load_data_files
    dc.append(load_data(df, auto_data))
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/core/data_collection.py", line 72, in append
    self._sync_link_manager()
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/core/data_collection.py", line 108, in _sync_link_manager
    for link in d.coordinate_links:
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/core/data.py", line 866, in coordinate_links
    self.coords, i)
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glue/core/component_link.py", line 267, in __init__
    comp_from = [comp_from[i] for i in self.from_needed]
IndexError: list index out of range
```

I suspect it is in some way related to an astropy version/numpy1.9/1.10 version issue, but I can't figure out what/why/how.

**Comment by astrofrog** [comment] 2015-11-18 16:22
@keflavich - is this with the latest developer version of Glue? Or the latest version from Anaconda?

**Comment by keflavich** [comment] 2015-11-18 16:23
conda most recently, but I've been getting errors with both

**Comment by keflavich** [comment] 2015-11-18 16:26
this message in particular: `RuntimeError: module compiled against API version a but this version of numpy is 9` worries me.

**Comment by keflavich** [comment] 2015-11-18 16:29
Actually, this issue is specific to a FITS file:
```
SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -32 / array data type
NAXIS   =                    3 / number of array dimensions
NAXIS1  =                  586
NAXIS2  =                  399
NAXIS3  =                  801
DATAMIN = -0.7568063259125E+01         /
DATAMAX =  0.7546112537384E+01         /
BUNIT   = 'K (Tmb)     '               /
CROTA1  =  0.0000000000000E+00         /
CROTA2  =  0.0000000000000E+00         /
CROTA3  =  0.0000000000000E+00         /
CROTA4  =  0.0000000000000E+00         /
OBJECT  = 'G341        '               /
GLAT    =  0.3410000000000E+03         / Galactic latitude
GLON    =  0.0000000000000E+00         / Galactic longitude
EQUINOX =  0.2000000000000E+04         /
LINE    = 'H2CO303-202 '               /
ALTRPIX =  0.4010000000000E+03         /
ALTRVAL =  0.2182221900000E+12         /
RESTFREQ=  0.2182221900000E+12         /
VELO-LSR=  0.0000000000000E+00         /
VELREF  =                  257         /
BMAJ    =  0.8435291128836E-02         /
BMIN    =  0.8435291128836E-02         /
BPA     =  0.0000000000000E+00         /
ORIGIN  = 'GILDAS Consortium  '        /
DATE    = '2015-09-28T00:00:00.00'     / Date written
WCSAXES =                    3
CRPIX1  =       199.1415386283
CRPIX2  =       201.1124356188
CRPIX3  =                401.0
CDELT1  =        -0.0026388889
CDELT2  =         0.0026388889
CDELT3  =                500.0
CUNIT1  = 'deg     '
CUNIT2  = 'deg     '
CUNIT3  = 'm s-1   '
CTYPE1  = 'GLON-SFL'
CTYPE2  = 'GLAT-SFL'
CTYPE3  = 'VRAD    '
CRVAL1  =                341.0
CRVAL2  =                  0.0
CRVAL3  =                  0.0
PV1_0   =                  1.0
PV1_1   =                  0.0
PV1_2   =                  0.0
LONPOLE =                  0.0
LATPOLE =                 90.0
RESTFRQ =       218222190000.0
SPECSYS = 'LSRK    '
END
```

**Comment by astrofrog** [comment] 2015-11-18 17:39
> this message in particular: RuntimeError: module compiled against API version a but this version of numpy is 9 worries me.

This indicates that you upgraded Numpy without upgrading for example Astropy. Make sure you run ``conda install numpy=1.10 astropy matplotlib`` and include any other module that relies on Numpy to make sure they get updated too.

Once you've done that, can you check whether the error still occurs?

**Comment by astrofrog** [comment] 2015-11-18 17:45
For the conda issues, I opened an issue here: https://github.com/conda/conda/issues/1841

**Comment by astrofrog** [comment] 2015-11-19 15:05
@keflavich - ok, I can reproduce the issue here. The issue is that the header contains ``CROTA4``. I will see if I can make the reader more robust to this kind of issue.

**Comment by keflavich** [comment] 2015-11-19 15:17
Thanks.  This header was written by `SpectralCube`, so I think there is
also a bug there (or in `astropy.wcs`) that should filter out such bad
header keywords.  I normally would have caught that issue myself, but I was
reporting this from within a meeting... sorry about the messy Issue.

On Thu, Nov 19, 2015 at 4:05 PM, Thomas Robitaille <notifications@github.com
> wrote:

> @keflavich <https://github.com/keflavich> - ok, I can reproduce the issue
> here. The issue is that the header contains CROTA4. I will see if I can
> make the reader more robust to this kind of issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/glue-viz/glue/issues/792#issuecomment-158083312>.
>



-- 
Adam

**Comment by astrofrog** [comment] 2016-04-01 01:48
Closing in favor of https://github.com/glue-viz/glue/issues/904

**Closed by astrofrog** 2016-04-01 01:48 UTC
Labels: io
