### ISSUE TITLE
XLS / XLSX loader issue. numpy.int64

### ISSUE THREAD

**Issue by kmshort** [glue-viz/glue#714] opened 2015-08-05 05:11 UTC
Hi again,

Anaconda 2.3 here, Win64.
Loading an XLSX spreadsheet generated in Excel 2013/64 causes the following 'Data Load Error':

```python
Error message: 'numpy.int64' object has no attribute 'strip'

----
Traceback (most recent call last):
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\qt\qtutil.py", line 103, in data_wizard
    result = gdd.load_data()
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\qt\decorators.py", line 20, in result
    return func(*args, **kwargs)
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\qt\qtutil.py", line 172, in load_data
    d = load_data(path, factory=fac.function)
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\core\data_factories\helpers.py", line 247, in load_data
    d = as_list(factory(path, **kwargs))
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\core\data_factories\helpers.py", line 323, in auto_data
    return fac(filename, *args, **kwargs)
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\core\data_factories\excel.py", line 22, in panda_read_excel
    return panda_process(indf)
  File "C:\Users\joebloggs\AppData\Local\Continuum\Anaconda\lib\site-packages\glue\core\data_factories\pandas.py", line 33, in panda_process
    name = name.strip()
AttributeError: 'numpy.int64' object has no attribute 'strip'
----
```

regards

**Comment by astrofrog** [comment] 2015-08-08 16:10
@kmshort - could you send the spreadsheet to thomas.robitaille@gmail.com, and I can look into it?

**Comment by astrofrog** [comment] 2015-08-18 18:15
Ok, I can reproduce this - this occurs when there are no column titles in a spreadsheet.

**Comment by astrofrog** [comment] 2015-08-18 18:24
So if I create an excel spreadsheet with only one column and 3 values, say:

```
1
2
3
```

then using ``read_excel`` from pandas produces a dataframe that looks like:

```
   1
0  2
1  3
```

If I pass ``header=None``, I get:

```
   0
0  1
1  2
2  2
```

either way, the column name is actually an int which is the cause of this error. A quick fix would be to simply always call ``str`` on the column name.

At the moment, we don't really have a good way to let the user decide if there is a header row or not, so this might be worth considering.

@kmshort - in the mean time, an easy fix for this is just to make sure the columns in the excel spreadsheet have names.

**Comment by kmshort** [comment] 2015-08-20 07:08
Hi Thomas,

Thanks for looking into this. I agree, str(header) should be the default,
and be switchable to int IF the value is an int, and if the user requests
it.

In the meantime, I will alter my VBA code to insert headers during
processing.

cheers,
Kieran

On Wed, Aug 19, 2015 at 4:24 AM, Thomas Robitaille <notifications@github.com

**Closed** 2015-08-25 14:21 UTC
Labels: bug
