### ISSUE TITLE
glue logger interfering with jwst logger

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue#2278] opened 2022-02-23 19:26 UTC
As reported by @jemorrison , `import glue` causes `jwst` to double-log. Is there a way to turn off the `glue` logger?

[🐱](https://jira.stsci.edu/browse/JP-2280)

**Comment by astrofrog** [comment] 2022-03-10 10:06
@pllim - could you provide a minimal example to reproduce this, including data files if needed? I don't really know how to use the jwst pipeline and don't have access to files to pass to it.

**Comment by pllim** [comment] 2022-03-10 14:27
I don't either. I am just the messenger. @orifox or @jemorrison can help you.

**Comment by orifox** [comment] 2022-03-10 14:30
Let me know if the JIRA ticket has enough info? Not sure if you are using this as a reference yet or not? I sent it via Slack since I don't know the policy about posting tickets here.

**Comment by orifox** [comment] 2022-03-10 14:38
Transferring ticket text here.

GLUE apparently has a logger that competed with other loggers, specifically the JWST pipeline.

In the JWST example (which is a common use case), even if the logger is directed to an output file, the GLUE logger will force output in the Jupyter notebook. More logging then occurs when jdaviz is opened. Meaning the tool opens below any logging, which can be confusing to the user.

With the most recent "jwst" pipeline release, logging not as bad. But this makes jdaviz beholden to possible logging in "jwst" package. We want to avoid that. Somehow need to incorporate the code above to turn off logging (in jdaviz or glue or...?)

I want to stress that this is NOT just a problem in Jdaviz. The double logging ends up resulting in a log when running the jwst pipeline, which in some cases can be pages and pages long. Even if the user directs the logging to an output file, the logging goes to the file AND the notebook. This should not happen.

Sample notebook emailed and data set attached to illustrate problem.

![screenshot](https://user-images.githubusercontent.com/5994975/157684474-5673a899-15ee-4bc2-abc4-1df3d2611447.jpg)

**Comment by orifox** [comment] 2022-03-10 23:53
The new Glue PR (https://github.com/glue-viz/glue/pull/2281) is getting closer! That's great.
However, if you run the following variation of the command in Cell 5 of the notebook (and don’t direct the jwst logging to an output file), you now get half the number of loggings still appear (in this case, one message, not two like before). I’ve also updated the git issue.

result = calwebb_detector1.Detector1Pipeline.call(uncal_file)

<img width="1131" alt="Screen Shot 2022-03-09 at 9 26 43 AM" src="https://user-images.githubusercontent.com/5994975/157775042-c73a0434-9e90-4307-9657-151f0e430616.png">

**Comment by pllim** [comment] 2022-03-11 01:34
Are you sure that is the correct screenshot? I don't see any logging in there.

Also, when you don't redirect the jwst logger to file, it is going to log. There is no way to completely suppress jwst logging yet and no one can fix that except for jwst.

**Comment by orifox** [comment] 2022-03-11 04:27
@pllim That was indeed the wrong screenshot. Thanks! 

As for logging, that's what I don't understand. If you don't run the pipeline, the logger doesn't get turned on. So there must be a way to turn the logger on/off even without getting jwst involved.

**Comment by pllim** [comment] 2022-03-11 05:53
@orifox , and this is after you turn off warnings in Python?

```python
import warnings
warnings.simplefilter('ignore')
```

**Comment by orifox** [comment] 2022-03-11 05:59
Hey @pllim, you should be sleeping. I'm on shift late in the JWST MOC late tonight. But yes, even when you run that command. You can run the notebook I posted in Slack (but exclude Cell 4). And you can replicate the error message above. If you skip Cell 5 (the pipeline itself) you won't get any error message when opening jdaviz.

**Comment by astrofrog** [comment] 2022-03-11 08:08
Isn't that message genuine though in the sense that a deprecated feature is being used?

**Comment by orifox** [comment] 2022-03-11 08:15
I guess that's what I don't understand. Why is it showing up after I run the pipeline, but doesn't show up if I don't run the pipeline?

**Comment by pllim** [comment] 2022-03-11 12:39
I think now we're in the territory where the pipeline is taking over the Python warning system, which I think we already know is a problem and pipeline has a ticket open to suppress logging? Maybe @jemorrison can clarify.

**Comment by jemorrison** [comment] 2022-03-11 17:48
Catching up on the activity. Do I need to import a new version of glue ? Or just add 
import warnings
warnings.simplefilter('ignore')
to the notebook. 
 I want to try and reproduce this logging issue on my notebook to see what remaining issues there are

**Comment by pllim** [comment] 2022-03-11 19:01
You would need to install glue from this PR branch and then use Ori's notebook.

**Comment by orifox** [comment] 2022-03-11 20:39
Hi @jemorrison I just sent you the notebook. For some reason, GIT doesn't allow me to attach it here.

**Comment by orifox** [comment] 2022-03-17 16:54
That is correct and consistent what I was trying to say above.

**Comment by astrofrog** [comment] 2022-05-19 13:48
I am closing this as I think it was addressed on the glue side with #2281

**Closed by astrofrog** 2022-05-19 13:48 UTC
